gazebo_ros_control:
  pid_gains:
    j1:
      p: 1000
      d: 1
      i: 1
      i_clamp: 1
    j2:
      p: 1000
      d: 1
      i: 1
      i_clamp: 1
    j3:
      p: 1000
      d: 1
      i: 1
      i_clamp: 1
    j4:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    j5:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    j6:
      p: 10
      d: 0.1
      i: 0.1
      i_clamp: 0.1